import type { Metadata } from 'next';
import Bookshelf from '@/components/Bookshelf';
import { LinkItem } from '@/components/RotatingBookshelf';

export const metadata: Metadata = {
  title: 'AI 跳马 - 思维书架',
  description: '一个展示思维的跃层书架，藏书万卷，思想无限',
};

// 示例数据 - 展示不同重要度和私密性的书籍
const sampleShelves = [
  {
    id: 'loft-1',
    name: '高度私密 - 核心思想',
    level: 'loft' as const,
    privacy: 'private' as const,
    books: [
      {
        id: 'book-1',
        title: '人生哲学',
        link: 'https://example.com/philosophy',
        color: 'purple' as const,
        thickness: 'thick' as const,
        height: 'tall' as const,
        importance: 'high' as const,
        privacy: 'private' as const,
        password: 'secret123',
        hasBookmark: true,
      },
      {
        id: 'book-2',
        title: '创业计划',
        link: 'https://example.com/startup',
        color: 'red' as const,
        thickness: 'thick' as const,
        height: 'tall' as const,
        importance: 'high' as const,
        privacy: 'private' as const,
        password: 'startup2024',
        angle: 'tilted' as const,
      },
      {
        id: 'book-3',
        title: '财务目标',
        link: 'https://example.com/finance',
        color: 'amber' as const,
        thickness: 'medium' as const,
        height: 'medium' as const,
        importance: 'high' as const,
        privacy: 'private' as const,
        password: 'money',
      },
    ],
  },
  {
    id: 'loft-2',
    name: '半私密 - 个人感悟',
    level: 'loft' as const,
    privacy: 'semi-private' as const,
    books: [
      {
        id: 'book-4',
        title: '读书笔记',
        link: 'https://example.com/notes',
        color: 'teal' as const,
        thickness: 'medium' as const,
        height: 'medium' as const,
        importance: 'medium' as const,
        privacy: 'semi-private' as const,
      },
      {
        id: 'book-5',
        title: '旅行记忆',
        link: 'https://example.com/travel',
        color: 'pink' as const,
        thickness: 'medium' as const,
        height: 'tall' as const,
        importance: 'medium' as const,
        privacy: 'semi-private' as const,
        angle: 'tilted' as const,
        hasBookmark: true,
      },
    ],
  },
  {
    id: 'main-1',
    name: '核心技术',
    level: 'main' as const,
    books: [
      {
        id: 'book-7',
        title: 'JavaScript高级编程',
        link: 'https://example.com/js',
        color: 'blue' as const,
        thickness: 'thick' as const,
        height: 'tall' as const,
        importance: 'high' as const,
        privacy: 'public' as const,
        hasBookmark: true,
      },
      {
        id: 'book-8',
        title: 'React设计模式',
        link: 'https://example.com/react',
        color: 'blue' as const,
        thickness: 'medium' as const,
        height: 'medium' as const,
        importance: 'high' as const,
        privacy: 'public' as const,
      },
      {
        id: 'book-9',
        title: 'TypeScript实战',
        link: 'https://example.com/ts',
        color: 'indigo' as const,
        thickness: 'medium' as const,
        height: 'tall' as const,
        importance: 'medium' as const,
        privacy: 'public' as const,
        angle: 'tilted' as const,
      },
      {
        id: 'book-10',
        title: 'Node.js后端开发',
        link: 'https://example.com/node',
        color: 'green' as const,
        thickness: 'thick' as const,
        height: 'medium' as const,
        importance: 'medium' as const,
        privacy: 'public' as const,
      },
    ],
  },
  {
    id: 'main-2',
    name: '人工智能',
    level: 'main' as const,
    books: [
      {
        id: 'book-12',
        title: '机器学习基础',
        link: 'https://example.com/ml',
        color: 'purple' as const,
        thickness: 'thick' as const,
        height: 'tall' as const,
        importance: 'high' as const,
        privacy: 'public' as const,
        hasBookmark: true,
      },
      {
        id: 'book-13',
        title: '深度学习入门',
        link: 'https://example.com/dl',
        color: 'purple' as const,
        thickness: 'medium' as const,
        height: 'medium' as const,
        importance: 'medium' as const,
        privacy: 'public' as const,
      },
      {
        id: 'book-14',
        title: 'GPT与大模型',
        link: 'https://example.com/llm',
        color: 'indigo' as const,
        thickness: 'thick' as const,
        height: 'tall' as const,
        importance: 'high' as const,
        privacy: 'public' as const,
        angle: 'tilted' as const,
      },
    ],
  },
  {
    id: 'main-3',
    name: '产品思维',
    level: 'main' as const,
    books: [
      {
        id: 'book-16',
        title: '用户体验设计',
        link: 'https://example.com/ux',
        color: 'teal' as const,
        thickness: 'medium' as const,
        height: 'medium' as const,
        importance: 'medium' as const,
        privacy: 'public' as const,
      },
      {
        id: 'book-17',
        title: '产品方法论',
        link: 'https://example.com/product',
        color: 'amber' as const,
        thickness: 'thick' as const,
        height: 'tall' as const,
        importance: 'high' as const,
        privacy: 'public' as const,
        hasBookmark: true,
      },
      {
        id: 'book-18',
        title: '敏捷开发',
        link: 'https://example.com/agile',
        color: 'green' as const,
        thickness: 'medium' as const,
        height: 'medium' as const,
        importance: 'medium' as const,
        privacy: 'public' as const,
      },
    ],
  },
  {
    id: 'main-4',
    name: '生活随笔',
    level: 'main' as const,
    books: [
      {
        id: 'book-21',
        title: '晨间日记',
        link: 'https://example.com/diary',
        color: 'pink' as const,
        thickness: 'thin' as const,
        height: 'short' as const,
        importance: 'low' as const,
        privacy: 'public' as const,
      },
      {
        id: 'book-22',
        title: '摄影集',
        link: 'https://example.com/photos',
        color: 'teal' as const,
        thickness: 'medium' as const,
        height: 'medium' as const,
        importance: 'medium' as const,
        privacy: 'public' as const,
        hasBookmark: true,
      },
      {
        id: 'book-23',
        title: '电影清单',
        link: 'https://example.com/movies',
        color: 'red' as const,
        thickness: 'thin' as const,
        height: 'short' as const,
        importance: 'low' as const,
        privacy: 'public' as const,
        angle: 'stacked' as const,
      },
    ],
  },
];

// 常用链接数据
const sampleLinks: LinkItem[] = [
  {
    id: 'link-1',
    title: 'GitHub',
    url: 'https://github.com',
    icon: '🐙',
    color: 'gray',
    description: '代码托管平台',
  },
  {
    id: 'link-2',
    title: 'Google',
    url: 'https://google.com',
    icon: '🔍',
    color: 'blue',
    description: '搜索引擎',
  },
  {
    id: 'link-3',
    title: 'ChatGPT',
    url: 'https://chat.openai.com',
    icon: '🤖',
    color: 'green',
    description: 'AI 对话助手',
  },
  {
    id: 'link-4',
    title: '掘金',
    url: 'https://juejin.cn',
    icon: '💎',
    color: 'amber',
    description: '技术社区',
  },
  {
    id: 'link-5',
    title: '知乎',
    url: 'https://zhihu.com',
    icon: '📘',
    color: 'blue',
    description: '问答社区',
  },
  {
    id: 'link-6',
    title: 'Bilibili',
    url: 'https://bilibili.com',
    icon: '📺',
    color: 'pink',
    description: '视频平台',
  },
  {
    id: 'link-7',
    title: 'MDN',
    url: 'https://developer.mozilla.org',
    icon: '📖',
    color: 'indigo',
    description: 'Web 开发文档',
  },
  {
    id: 'link-8',
    title: 'Vercel',
    url: 'https://vercel.com',
    icon: '▲',
    color: 'gray',
    description: '部署平台',
  },
];

export default function Home() {
  return <Bookshelf shelves={sampleShelves} links={sampleLinks} />;
}
